pipeline
{

agent {
  label 'server2'
}

tools {
  maven 'mymaven'
}

stages{
    
    stage('build')
    {
        steps{
            sh 'maven clean package'
        }
       
        post {
            success {
                archiveArtifacts artifacts: '**/target/*.war'
                }
            }

    }


}

}